export const FERRO_CORE = {
  name: 'FERRO CORE',
  price: 80,
  subtitle: '16 biomarcatori. Il pannello che ogni atleta dovrebbe fare',
  description: 'Screening metabolico, epatico, renale, tiroideo, marziale + Testosterone + Vitamina D + PCR. Tutto in un unico pannello obbligatorio.',
  highlights: ['Testosterone', 'Vitamina D'],
  biomarkers: [
    'Emocromo completo (con formula e piastrine)',
    'Glicemia a digiuno',
    'Colesterolo totale',
    'HDL-C',
    'LDL-C',
    'Trigliceridi',
    'Creatinina',
    'eGFR (CKD-EPI)',
    'ALT',
    'GGT',
    'TSH',
    'Ferritina',
    'Vitamina D (25-OH)',
    'Testosterone totale',
    'PCR (C-Reactive Protein)',
    'Esame urine completo',
  ]
};

export const MODULES = [
  {
    id: 'androgeno',
    name: 'FERRO ANDROGENO',
    price: 125,
    icon: 'dna',
    tags: ['Uomini sintomatici', 'TRT', 'Ex/attuali AAS'],
    desc: 'Asse androgenico completo + coagulazione + omocisteina',
    tests: 12,
    gender: 'UOMO',
    biomarkers: ['SHBG', 'Testosterone libero (calcolato)', 'LH', 'FSH', 'Estradiolo', 'Prolattina', 'PSA', 'Fibrinogeno', 'D-dimero', 'PT/INR', 'APTT', 'Omocisteina'],
  },
  {
    id: 'cuore',
    name: 'FERRO CUORE',
    price: 23,
    icon: 'heart',
    tags: ['Familiarità CVD', 'AAS', 'Ipertensione'],
    desc: 'Rischio CV avanzato: ApoB, Lp(a), VES, Acido urico',
    tests: 4,
    biomarkers: ['ApoB', 'Lp(a)', 'VES', 'Acido urico'],
  },
  {
    id: 'reni',
    name: 'FERRO RENI',
    price: 28,
    icon: 'kidney',
    tags: ['Bodybuilder', 'Iperproteica', 'Diuretici'],
    desc: 'Funzione renale avanzata + elettroliti',
    tests: 8,
    biomarkers: ['Cistatina C', 'Azotemia (BUN/Urea)', 'Sodio', 'Potassio', 'Calcio', 'Fosforo', 'Magnesio', 'Cloro'],
  },
  {
    id: 'fegato',
    name: 'FERRO FEGATO',
    price: 12,
    icon: 'liver',
    tags: ['AAS orali', 'Alcol', 'Farmaci epatotossici'],
    desc: 'Profilo epatico completo',
    tests: 5,
    biomarkers: ['AST', 'Bilirubina totale/diretta', 'Fosfatasi alcalina (ALP)', 'Albumina', 'Proteine totali'],
  },
  {
    id: 'metabolico',
    name: 'FERRO METABOLICO',
    price: 33,
    icon: 'metabolism',
    tags: ['Overfat', 'Cut difficile', 'Uso GH', 'Stress'],
    desc: 'Insulino-resistenza + cortisolo',
    tests: 4,
    biomarkers: ['HbA1c', 'Insulina a digiuno', 'HOMA-IR (calcolato)', 'Cortisolo mattutino'],
  },
  {
    id: 'tiroide',
    name: 'FERRO TIROIDE',
    price: 40,
    icon: 'thyroid',
    tags: ['TSH alterato', 'Sospetto autoimmune'],
    desc: 'Profilo tiroideo completo + autoimmunità',
    tests: 4,
    biomarkers: ['fT4', 'fT3', 'Anti-TPO', 'Anti-Tg'],
  },
  {
    id: 'recovery',
    name: 'FERRO RECOVERY',
    price: 43,
    icon: 'recovery',
    tags: ['Fatigue', 'Diete restrittive', 'Endurance'],
    desc: 'Assetto marziale completo + B12/Folati',
    tests: 7,
    biomarkers: ['Sideremia', 'Transferrina', 'Saturazione transferrina', 'TIBC', 'Vitamina B12', 'Folati', 'Reticolociti'],
  },
  {
    id: 'donna',
    name: 'FERRO DONNA',
    price: 65,
    icon: 'woman',
    tags: ['Peri-menopausa', 'Amenorrea', 'PCOS', 'RED-S'],
    desc: 'Asse ormonale femminile completo',
    tests: 6,
    gender: 'DONNA',
    biomarkers: ['FSH', 'Estradiolo', 'Progesterone', 'Prolattina', 'DHEA-S', 'LH'],
  },
];

export const FEATURES = [
  {
    title: 'TESTOSTERONE',
    desc: 'Incluso nel FERRO CORE, non come "extra". Perché se ti alleni seriamente, il testosterone non è un lusso, è un dato che devi conoscere. Nessun competitor lo mette nel pannello base.',
  },
  {
    title: 'VITAMINA D',
    desc: 'Il 70% di chi si allena indoor è carente e non lo sa. Ossa, muscoli, immunità, umore: tutto passa da qui. Nel FERRO CORE di default, perché non ha senso scoprirlo dopo.',
  },
];
